"""export_workout — emit a Zwift .zwo (and optionally .fit) for a generated workout.

Args:
    --kind ...           same as generate_workout.py
    --duration-min N
    --template STR
    --name STR
    --out PATH           output .zwo path; default: workouts/<name>.zwo
    --push-to-garmin     emit a .fit file too. Honours TM_GARMIN_DRYRUN.

Output:
    {"zwo_path": "...", "fit_path": ... | null, "tss": float}

Per CLAUDE.md rule #4, --push-to-garmin requires explicit confirmation in
the calling turn. This tool itself only writes a local file; pushing it
to a watch is a separate step.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

from _common import REPO_ROOT, emit, fail, log  # type: ignore[import-not-found]
from analysis.workouts import build_workout, estimate_tss, to_zwo


def _parse_args(argv: list[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--kind", required=True)
    p.add_argument("--duration-min", type=int, default=None)
    p.add_argument("--template", default=None)
    p.add_argument("--name", default=None)
    p.add_argument("--out", default=None)
    p.add_argument("--push-to-garmin", action="store_true")
    return p.parse_args(argv)


def main(argv: list[str]) -> None:
    args = _parse_args(argv)
    try:
        steps = build_workout(args.kind, args.duration_min, args.template)
    except ValueError as e:
        fail(str(e))

    total_s = sum(s["duration_s"] for s in steps)
    name = args.name or f"{args.kind.upper()}{(' ' + args.template) if args.template else ''} {total_s // 60}min"

    out_dir = REPO_ROOT / "workouts"
    out_dir.mkdir(exist_ok=True)
    out = Path(args.out) if args.out else out_dir / f"{name.replace(' ', '_')}.zwo"
    out.write_text(to_zwo(steps, name, f"Auto-generated by Training-Mate. Estimated TSS {estimate_tss(steps)}"))

    fit_path = None
    if args.push_to_garmin:
        # Per CLAUDE.md rule #4 + PLAN.md: gated by TM_GARMIN_DRYRUN.
        dryrun = os.getenv("TM_GARMIN_DRYRUN", "true").lower() not in ("0", "false", "no")
        if dryrun:
            log("[export] TM_GARMIN_DRYRUN=true — not writing .fit. Set TM_GARMIN_DRYRUN=false in .env to enable.")
        else:
            # FIT writing requires fit-tool which we haven't pinned yet — defer
            # to a later phase. For now, surface a clear placeholder.
            log("[export] FIT writing not yet implemented — pin `fit-tool` and add a writer in M5+.")

    emit(
        {
            "zwo_path": str(out),
            "fit_path": fit_path,
            "tss": estimate_tss(steps),
            "duration_min": total_s // 60,
            "kind": args.kind,
            "template": args.template,
        }
    )


if __name__ == "__main__":
    main(sys.argv[1:])
